#ResilientTransactionProcesssor.py
'''
1. Data Processing:
o Read the logs.csv file. 
##### DONE
o Calculate the Total Spend and Average Transaction per Category per Date. 
##### Done (could change up a bit)

2. Error Handling & amp; Resilience:
o The script must not crash when encountering malformed rows (e.g.,
missing dates, non-numeric amounts, or extra columns).
##### Done (to my testing)
o Identify and log all malformed rows to a separate file named errors.log,
including the line number and a brief description of the error.
##### Done (only check if there is no info there or if row is too big.)

3. Output:
o Save the final calculated data to a file named processed_data.json.
##### Done (save to file but don't know if it is formated properly)

4. Constraints:
o Assume this file could eventually grow to millions of rows; prioritize
memory efficiency (e.g., use generators or efficient data structures).
###### Tested with 1 million and seemed fine
o You may use the Python Standard Library or pandas. Please state which
you chose and why.
###### I used standard python because 
       1) I understand it more than pandas 
       2) I think it is important to know standard python for when I cant use other Librarys.
       3) I think the standard library works just fine for this task.

Deliverables
 The .py script.
 A requirements.txt file (if using external libraries).
 The resulting processed_data.json and errors.log generated by your script.

Questions
1. How should we acccount for the $ in the amount column? 
Should we remove it and convert to a float, or should we consider it an error?
- I think we should remove the $ and convert to a float
'''
import csv  # Used for reading CSV file
import os   # Used for deleting errors.log
import json # Used for making json file
from datetime import datetime # Used for checking if date is valid

# Makes list for errors.log
def checkRow(lineCount, message):
    newList = [lineCount, message]
    return newList

# Checks if each section in the row is valid
def isRowBad(row, catlist):
    if len(row) == 4:

        # Date check
        try:
            datetime.strptime(row[0], '%Y-%m-%d')
        except ValueError:
            return False, "Invalid date format"
        
        # Category check
        for i in range(1):
            if row[1] == catlist[0]:
                break
            elif row[1] == catlist[1]:
                break
            elif row[1] == catlist[2]:
                break
            elif row[1] == catlist[3]:
                break
            else:
                return False, "Missing category"
            
        # Price check
        if row[2] != '' :#and row[2] != "EXEMPT":
            numTest = row[2]
            try:
                if '$' in row[2]:
                    numTest = row[2].replace('$', '')
                num = float(numTest)
            except ValueError:
                return False, "Non-numeric amount"
        elif row[2] == '':
            return False, "Non-numeric amount"

        # Comment check
        if row[3] == '':
            return False, "No comment added"
    # Check if there are too many or not enough entrys   
    elif len(row) > 4:
        return False, "Too many entrys"
    elif len(row) < 4:
        return False, "Not enough entrys"
    return True, None

# Converts string to float and removes $ if there is one
def stringTofloat(value):
    if isinstance(value, str):
        try:
            if "$" in value:
                value = value.replace("$", "")
            return float(value)
        except ValueError:
            return value
    return value

# Makes a list with the date, category, and total spend
def foundDate(row):
    newList = [row[0], row[1],stringTofloat(row[2])]
    return newList

# Makes a list with the date, category, and total spend (without converting to float)
def newDate(row):
    newlist = [row[0], row[1], row[2]]
    return newlist

# Makes a list with the date, category, total spend, and average transaction
def makeCorrectList(currentList):
    length = len(currentList)
    total = 0
    
    if length > 1:
        for i in range(length):
            total += stringTofloat(currentList[i][2])
        newList = [currentList[0][0], currentList[0][1], total, total/length]
            
    elif length == 1:
        total = stringTofloat(currentList[0][2])
        newList = [currentList[0][0], currentList[0][1], total, total]    
    return newList

# Clears the list for the next date
def clearList(currentList):
    currentList.clear()

# Reads csv file
with open('logs.csv', mode = 'r', newline= '') as file:
    csv_reader = csv.reader(file)
    dateCheck = ""
    listforJsonFile = []
    groceriesList = []
    diningList = []
    utilitiesList = []
    electronicsList =[]
    badLineList = []
    lineCounter =1
    categoryNameList = ["Groceries", "Dining", "Utilities", "Electronics"]

    next(csv_reader, None)  # Skips heading
    for row in csv_reader:  # reads CSV line by line
        lineCounter += 1

        # Skips row if the row has an error in it
        if isRowBad(row, categoryNameList)[0] == False:
            badLineList.append(checkRow("Line " + str(lineCounter)+ ": ",
                                         isRowBad(row, categoryNameList)[1]))
            continue

        # If the list is empty add the first date
        if dateCheck == "": 
            if row[1] == categoryNameList[0]:
                groceriesList.append(foundDate(row))
            elif row[1] == categoryNameList[1]:
                diningList.append(foundDate(row))
            elif row[1] == categoryNameList[2]:
                utilitiesList.append(foundDate(row))
            elif row[1] == categoryNameList[3]:
                electronicsList.append(foundDate(row))
            dateCheck = row[0]

        # If the date is the same as the last one add to the list
        elif row[0] == dateCheck:
            if row[1] == categoryNameList[0]:
                groceriesList.append(foundDate(row))
            elif row[1] == categoryNameList[1]:
                diningList.append(foundDate(row))
            elif row[1] == categoryNameList[2]:
                utilitiesList.append(foundDate(row))
            elif row[1] == categoryNameList[3]:
                electronicsList.append(foundDate(row))
            dateCheck = row[0]

        # If the date is different then the last one make a new entry 
        # in the json file and clear the list for the next date
        else:
            if len(groceriesList) > 0:
                listforJsonFile.append(makeCorrectList(groceriesList))
                clearList(groceriesList)
            if len(diningList) > 0:
                print(diningList, "dining list")
                listforJsonFile.append(makeCorrectList(diningList))
                clearList(diningList)
            if len(utilitiesList) > 0:
                print(utilitiesList, "utilities list")
                listforJsonFile.append(makeCorrectList(utilitiesList))
                clearList(utilitiesList)    
            if len(electronicsList) > 0:
                print(electronicsList, "electronics list")
                listforJsonFile.append(makeCorrectList(electronicsList))
                clearList(electronicsList)

            if row[1] == categoryNameList[0]:
                groceriesList.append(foundDate(row))
            elif row[1] == categoryNameList[1]:
                diningList.append(foundDate(row))
            elif row[1] == categoryNameList[2]:
                utilitiesList.append(foundDate(row))
            elif row[1] == categoryNameList[3]:
                electronicsList.append(foundDate(row))
            dateCheck = row[0]

# After the loop is done we need to check if there is any left over 
# data in the list and add it to the json file
if len(groceriesList) > 0:
    listforJsonFile.append(makeCorrectList(groceriesList))
    clearList(groceriesList)
if len(diningList) > 0:
    listforJsonFile.append(makeCorrectList(diningList))
    clearList(diningList)
if len(utilitiesList) > 0:
    listforJsonFile.append(makeCorrectList(utilitiesList))
    clearList(utilitiesList)    
if len(electronicsList) > 0:
    listforJsonFile.append(makeCorrectList(electronicsList))
    clearList(electronicsList)

# Changes int to string to write in files
def intToString(value):
    newString = str(value)
    return newString

filename = "errors.log"

# Remove old entrys to keep file up to date
if os.path.isfile(filename):
    os.remove(filename)

# Makes errors.log file
with open(filename, 'a') as f:
    for i in range(len(badLineList)):
        for j in range(2):
            if isinstance(badLineList[i][j], int):
                f.write(intToString(badLineList[i][j]))
                f.write(", ")  
            else:
                f.write(badLineList[i][j])
             
        f.write("\n")

result = {}

# Changes list to json format and writes to file
for date, category, total, average in listforJsonFile:
    if date not in result:
        result[date] = {}
    result[date][category] = {
        "total spend": total,
        "average transaction": average
    }
    with open('processed_data.json', 'w') as json_file:
        json.dump(result, json_file, indent=1)  
