#ResilientTransactionProcesssor.py


'''
1. Data Processing:
o Read the logs.csv file.

o Calculate the Total Spend and Average Transaction per Category per Date.
2. Error Handling & amp; Resilience:
o The script must not crash when encountering malformed rows (e.g.,
missing dates, non-numeric amounts, or extra columns).
o Identify and log all malformed rows to a separate file named errors.log,
including the line number and a brief description of the error.

3. Output:
o Save the final calculated data to a file named processed_data.json.
4. Constraints:
o Assume this file could eventually grow to millions of rows; prioritize
memory efficiency (e.g., use generators or efficient data structures).
o You may use the Python Standard Library or pandas. Please state which
you chose and why.

Deliverables
 The .py script.
 A requirements.txt file (if using external libraries).
 The resulting processed_data.json and errors.log generated by your script.



Questions
How are do you want avg to be calculated with excptions
how to deal with invaled dates for calculation?
Where does line counting start?
how should the json and errors.log file look?


'''


import csv
import os
import json

# Gets total and avg amount for category 
def categoryTotal(categoryList):
    listLength = len(categoryList)
    total = 0
    for i in range(listLength):
        try:
            num = float(categoryList[i])
            total += num
        except ValueError:
            categoryList[i] = 0
            listLength -= 1
    avg = total / listLength
    avg = round(avg, 2)
    return total, avg

# Make list for a category
def makeCategoryList(categoryName, lst):
    newList = []
    totals = categoryTotal(lst)
    newList += [categoryName, totals[0], totals[1]]
    return newList

# Checks and changes string to float and adds total for date
def dateTotal(amount1, amount2):
    try:
        if isinstance(amount1, float):
            num1 = amount1
            num2 = float(amount2)
            total = num1 + num2
            return total
        else:
            num1 = float(amount1)
            num2 = float(amount2)
            total = num1 + num2
            return total
    except ValueError:
        try:
            num1 = float(amount1)
            return num1
        except:
            try:
                num1 = float(amount2)
                return num1
            except:
                return None
     
def checkRow(lineCount, message):
    newList = [lineCount, message]
    return newList


# Reads csv file
with open('logs.csv', mode = 'r', newline= '') as file:
    csv_reader = csv.reader(file)
    spendingInfoListByDate = []
    spendingInfoListByCatagory = []
    groceriesList = []
    diningList = []
    utilitiesList = []
    electronicsList =[]
    badLineList = []
    lineCounter =1
    avgCounter = 0
    dateCounter = 0
    #badLineBool = False
    firstloop = True

    next(csv_reader, None) #skips heading
    for row in csv_reader:

        # Check each row to see if it is valid 
        lineCounter += 1
        if row[0] == '':
            badLineList.append(checkRow(lineCounter, "No date provided",))
        if row[1] == '':
            badLineList.append(checkRow(lineCounter, "Not a current catagory"))
        if row[2] == '':
            badLineList.append(checkRow(lineCounter, "Not valid price"))
        if row[3] == '':
            badLineList.append(checkRow(lineCounter, "No comment added"))
        elif len(row) > 4:
            badLineList.append(checkRow(lineCounter, "Too many entrys"))

        if firstloop == True:
            newRowList = [row[0], 0, 0]
            spendingInfoListByDate.append(newRowList)
            firstloop = False

        # Populate info for 
        if row[1] == "Groceries":
            groceriesList.append(row[2])
        elif row[1] == "Dining":
            diningList.append(row[2])
        elif row[1] == "Utilities":
            utilitiesList.append(row[2])
        elif row[1] == "Electronics":
            electronicsList.append(row[2])

        # Adds and avg the days spending
        if row[0] == spendingInfoListByDate[dateCounter][0]:
            avgCounter += 1
            if row[2] == "EXEMPT":
                avgCounter -= 1
            total = dateTotal(spendingInfoListByDate[dateCounter][1], row[2])
            spendingInfoListByDate[dateCounter][1] = total
            spendingInfoListByDate[dateCounter][2] = total / avgCounter
        else:   # Create new list for the day
            newRowList = [row[0], row[2], row[2]]
            spendingInfoListByDate.append(newRowList)
            dateCounter += 1
            if row[2] == "EXEMPT":
                avgCounter = 0
            else:
                avgCounter = 1
    
    categoryNameList = ["Groceries", "Dining", "Utilities", "Electronics"]
    categoryList = [groceriesList, diningList, utilitiesList, electronicsList]
    for i in range(len(categoryList)):
        spendingInfoListByCatagory.append(makeCategoryList(categoryNameList[i], categoryList[i]))

    # Populate the list for catagory
    for i in range(len(spendingInfoListByCatagory)):
        print(spendingInfoListByCatagory[i])

    print()
    for i in range(len(spendingInfoListByDate)):
        print(spendingInfoListByDate[i])

    print()
    for i in range(len(badLineList)):
        print(badLineList[i])


def intToString(value):
    newString = str(value)
    return newString


filename = "errors.log"

if os.path.isfile(filename):
    os.remove(filename)

with open(filename, 'a') as f:
    f.write("line, error\n")
    for i in range(len(badLineList)):
        for j in range(2):
            if isinstance(badLineList[i][j], int):
                f.write(intToString(badLineList[i][j]))
                f.write(", ")  
            else:
                f.write(badLineList[i][j])
             
        f.write("\n")



jsonFilename = "processed_data.json"
dateHeader = ["date", "total", "average"]
dictDate = [dict(zip(dateHeader, row)) for row in spendingInfoListByDate]
catHeader = ["category","total", "average"]
dictCat = [dict(zip(catHeader, row)) for row in spendingInfoListByCatagory]

with open(jsonFilename, 'w') as json_file:
    #f.write("date, total, avg")
    json.dump(dictCat, json_file, indent=1)
    json.dump(dictDate, json_file, indent=1)
